# -*- coding: utf-8 -*-
"""Generate responsive, modern-format derivatives of the site's content photographs.

The companion to build_heroes.py, for every photograph that is not a hero: the
cards, portraits, story images, avatars and the footer illustration. Writes
images/photo/<name>-<width>.{avif,webp} and a manifest, src/photos.js, that
main.js reads to build <picture> elements, so a browser downloads one file per
photo at the width it is actually shown rather than the full-size original.

Never upscales: a source narrower than a target width does not get that width.
Re-run after adding or replacing a photograph:  python build_photos.py
"""
import json, os
from PIL import Image

# Every photograph the pages show, keyed by the exact path main.js uses for it.
SOURCES = [
    "images/community-wellbeing.jpg",
    "images/education-and-opportunity.jpg",
    "images/health-and-dignity.avif",
    "images/youth-developlment.jpg",
    "images/clean-start.jpg",
    "images/bridge-to-learning-initiative.jpg",
    "images/well-and-whole-mobile-clinics.jpg",
    "images/the-craft-line.jpg",
    "images/the-craft-line2.jpg",
    "images/a-story-from-detroit.jpg",
    "images/second-chair-digital-hubs.jpg",
    "images/sit-with-us.jpg",
    "images/dana-whifield.jpg",
    "images/marcus-reyes.jpg",
    "images/priya-raman.jpg",
    "images/404-bridge.png",
]

# 480 covers a phone card, 800 a half-width column or a phone at 2x, 1200 the
# widest column on a large screen at 2x. Past that the bytes stop earning their place.
WIDTHS = [480, 800, 1200]
# The hero social-proof avatars are 32-40px circles, so they also get thumbnails.
EXTRA = {
    "images/dana-whifield.jpg": [96, 160],
    "images/marcus-reyes.jpg": [96, 160],
    "images/priya-raman.jpg": [96, 160],
}
OUT = "images/photo"
MANIFEST = "src/photos.js"

os.makedirs(OUT, exist_ok=True)
manifest = {}
before = after = 0

for src in SOURCES:
    im = Image.open(src).convert("RGB")
    stem = os.path.splitext(os.path.basename(src))[0]
    targets = sorted({w for w in WIDTHS + EXTRA.get(src, []) if w <= im.width})
    if im.width < max(WIDTHS) and im.width not in targets:
        # source sits below the widest step: offer its own width rather than round down
        targets.append(im.width)
    targets.sort()
    for w in targets:
        h = round(im.height * w / im.width)
        rs = im if w == im.width else im.resize((w, h), Image.Resampling.LANCZOS)
        big = w > 800
        # AVIF and WebP only: every current browser reads one of them, and the
        # <img> inside the <picture> keeps the original file as its fallback.
        for ext, kw in (("avif", dict(quality=45 if big else 52)),
                        ("webp", dict(quality=68 if big else 74, method=6))):
            p = "%s/%s-%d.%s" % (OUT, stem, w, ext)
            rs.save(p, **kw)
    largest_avif = os.path.getsize("%s/%s-%d.avif" % (OUT, stem, targets[-1]))
    before += os.path.getsize(src)
    after += largest_avif
    manifest[src] = {"stem": stem, "w": im.width, "h": im.height, "widths": targets}
    print("%-44s %4dx%-4d -> %s  (%d KB -> %d KB avif at %dw)" % (
        src, im.width, im.height, ", ".join("%dw" % w for w in targets),
        os.path.getsize(src) // 1024, largest_avif // 1024, targets[-1]))

with open(MANIFEST, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by build_photos.py - do not edit by hand; re-run the script.\n"
            "   Responsive derivatives of each content photograph, keyed by the path\n"
            "   main.js uses for it. Files live at images/photo/<stem>-<width>.<ext>. */\n")
    f.write("export default " + json.dumps(manifest, indent=2) + ";\n")

print("\nOriginals %d KB; largest AVIF of each %d KB. Manifest written to %s." % (
    before // 1024, after // 1024, MANIFEST))
