/** Theme for the HopeBridge site. Compiled into the <style> block of index.html.
 *  See README.md for the rebuild command. */
module.exports = {
  content: ['../index.html'],
  theme: {
    extend: {
      colors: {
        "surface":                   "#F5F5F0",
        "surface-dim":               "#DEDACF",
        "surface-bright":            "#F5F5F0",
        "surface-container-lowest":  "#ffffff",
        "surface-container-low":     "#F6F4EF",
        "surface-container":         "#F2EFE9",
        "surface-container-high":    "#EDE9E1",
        "surface-container-highest": "#E7E3DA",
        "on-surface":                "#14161A",
        "on-surface-variant":        "#4A5058",
        "inverse-surface":           "#1B2334",
        "inverse-on-surface":        "#F4F2EE",
        "outline":                   "#666B73",
        "outline-variant":           "#CFCABF",
        "surface-tint":              "#2C4468",
        "primary":                   "#173B2F",
        "on-primary":                "#ffffff",
        "primary-container":         "#1E3557",
        "on-primary-container":      "#7E97BE",
        "inverse-primary":           "#A9C1E4",
        "secondary":                 "#D97736",
        "on-secondary":              "#ffffff",
        "secondary-container":       "#D9A441",
        "on-secondary-container":    "#6E4A10",
        "tertiary":                  "#3A2A0B",
        "on-tertiary":               "#ffffff",
        "tertiary-container":        "#5A431A",
        "on-tertiary-container":     "#C8A96B",
        "error":                     "#ba1a1a",
        "on-error":                  "#ffffff",
        "error-container":           "#F7DAD6",
        "on-error-container":        "#93000a",
        "primary-fixed":             "#C9D8F0",
        "primary-fixed-dim":         "#A9C1E4",
        "on-primary-fixed":          "#0A1729",
        "on-primary-fixed-variant":  "#2C4468",
        "secondary-fixed":           "#F6E3C2",
        "secondary-fixed-dim":       "#E8BC63",
        "on-secondary-fixed":        "#2A1D04",
        "on-secondary-fixed-variant": "#5C4210",
        "tertiary-fixed":            "#F7E2CE",
        "tertiary-fixed-dim":        "#E3C489",
        "on-tertiary-fixed":         "#2C2007",
        "on-tertiary-fixed-variant": "#5E4715",
        "background":                "#F5F5F0",
        "on-background":             "#14161A",
        "surface-variant":           "#E7E3DA",
        "stone-surface":             "#EFEBE2",
        "charcoal-text":             "#14161A",
        "border-subtle":             "#E0DCD3",
      },
      borderRadius: { "DEFAULT": "0px", "none": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
      spacing: { "container-max": "1280px", "margin-mobile": "20px", "unit": "8px", "margin-desktop": "64px", "gutter": "32px" },
      maxWidth: { "container-max": "1280px" },
      fontFamily: { "display": ['Figtree', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'], "body": ['Figtree', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'], "sans": ['Figtree', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'] },
      fontSize: {
        "label-caps":  ["11px", { lineHeight: "16px", letterSpacing: "0.085em", fontWeight: "600" }],
        "label-caps-sm":["10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-sm":     ["13px", { lineHeight: "21px", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "body-lg":     ["17px", { lineHeight: "29px", fontWeight: "400" }],
        "quote":       ["21px", { lineHeight: "32px", letterSpacing: "-0.008em", fontWeight: "500" }],
        "quote-m":     ["19px", { lineHeight: "29px", letterSpacing: "-0.008em", fontWeight: "500" }],
        "title-md":    ["17px", { lineHeight: "25px", letterSpacing: "-0.004em", fontWeight: "600" }],
        "title-lg":    ["19px", { lineHeight: "27px", letterSpacing: "-0.008em", fontWeight: "600" }],
        "title-lg-m":  ["18px", { lineHeight: "26px", letterSpacing: "-0.008em", fontWeight: "600" }],
        "headline-sm": ["21px", { lineHeight: "29px", letterSpacing: "-0.012em", fontWeight: "600" }],
        "headline-sm-m":["19px", { lineHeight: "27px", letterSpacing: "-0.012em", fontWeight: "600" }],
        "headline-md": ["25px", { lineHeight: "33px", letterSpacing: "-0.014em", fontWeight: "600" }],
        "headline-md-m":["21px", { lineHeight: "29px", letterSpacing: "-0.014em", fontWeight: "600" }],
        "headline-lg": ["33px", { lineHeight: "42px", letterSpacing: "-0.018em", fontWeight: "700" }],
        "headline-lg-m":["26px", { lineHeight: "34px", letterSpacing: "-0.018em", fontWeight: "700" }],
        "display-lg":  ["44px", { lineHeight: "52px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-lg-m":["30px", { lineHeight: "38px", letterSpacing: "-0.022em", fontWeight: "700" }],
        "display-xl":  ["56px", { lineHeight: "62px", letterSpacing: "-0.028em", fontWeight: "700" }],
        "display-xl-mobile": ["34px", { lineHeight: "40px", letterSpacing: "-0.026em", fontWeight: "700" }]
      }
    }
  },
  plugins: [require('@tailwindcss/forms')]
};
