/* Generated by build_photos.py - do not edit by hand; re-run the script.
   Responsive derivatives of each content photograph, keyed by the path
   main.js uses for it. Files live at images/photo/<stem>-<width>.<ext>. */
export default {
  "images/community-wellbeing.jpg": {
    "stem": "community-wellbeing",
    "w": 1920,
    "h": 1279,
    "widths": [
      480,
      800,
      1200
    ]
  },
  "images/education-and-opportunity.jpg": {
    "stem": "education-and-opportunity",
    "w": 1080,
    "h": 1440,
    "widths": [
      480,
      800,
      1080
    ]
  },
  "images/health-and-dignity.avif": {
    "stem": "health-and-dignity",
    "w": 870,
    "h": 580,
    "widths": [
      480,
      800,
      870
    ]
  },
  "images/youth-developlment.jpg": {
    "stem": "youth-developlment",
    "w": 612,
    "h": 408,
    "widths": [
      480,
      612
    ]
  },
  "images/clean-start.jpg": {
    "stem": "clean-start",
    "w": 1024,
    "h": 1024,
    "widths": [
      480,
      800,
      1024
    ]
  },
  "images/bridge-to-learning-initiative.jpg": {
    "stem": "bridge-to-learning-initiative",
    "w": 1200,
    "h": 2133,
    "widths": [
      480,
      800,
      1200
    ]
  },
  "images/well-and-whole-mobile-clinics.jpg": {
    "stem": "well-and-whole-mobile-clinics",
    "w": 408,
    "h": 612,
    "widths": [
      408
    ]
  },
  "images/the-craft-line.jpg": {
    "stem": "the-craft-line",
    "w": 736,
    "h": 981,
    "widths": [
      480,
      736
    ]
  },
  "images/the-craft-line2.jpg": {
    "stem": "the-craft-line2",
    "w": 1200,
    "h": 1480,
    "widths": [
      480,
      800,
      1200
    ]
  },
  "images/a-story-from-detroit.jpg": {
    "stem": "a-story-from-detroit",
    "w": 1199,
    "h": 1372,
    "widths": [
      480,
      800,
      1199
    ]
  },
  "images/second-chair-digital-hubs.jpg": {
    "stem": "second-chair-digital-hubs",
    "w": 1200,
    "h": 675,
    "widths": [
      480,
      800,
      1200
    ]
  },
  "images/sit-with-us.jpg": {
    "stem": "sit-with-us",
    "w": 1200,
    "h": 1600,
    "widths": [
      480,
      800,
      1200
    ]
  },
  "images/dana-whifield.jpg": {
    "stem": "dana-whifield",
    "w": 736,
    "h": 1103,
    "widths": [
      96,
      160,
      480,
      736
    ]
  },
  "images/marcus-reyes.jpg": {
    "stem": "marcus-reyes",
    "w": 1200,
    "h": 1640,
    "widths": [
      96,
      160,
      480,
      800,
      1200
    ]
  },
  "images/priya-raman.jpg": {
    "stem": "priya-raman",
    "w": 1200,
    "h": 1800,
    "widths": [
      96,
      160,
      480,
      800,
      1200
    ]
  },
  "images/404-bridge.png": {
    "stem": "404-bridge",
    "w": 1448,
    "h": 1086,
    "widths": [
      480,
      800,
      1200
    ]
  }
};
